create table if not exists public.xavier_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  memory_enabled boolean not null default true,
  retention_days integer not null default 90 check (retention_days between 7 and 3650),
  monthly_message_limit integer not null default 1000 check (monthly_message_limit between 10 and 100000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.xavier_telegram_connections (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  bot_id bigint not null,
  bot_username text,
  bot_display_name text,
  encrypted_bot_token text not null,
  webhook_secret_hash text not null,
  status text not null default 'active' check (status in ('active', 'disconnected', 'error')),
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_verified_at timestamptz
);

create unique index if not exists xavier_telegram_connections_active_user_idx
  on public.xavier_telegram_connections (user_id)
  where status = 'active';

create index if not exists xavier_telegram_connections_user_created_idx
  on public.xavier_telegram_connections (user_id, created_at desc);

create table if not exists public.xavier_conversations (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  channel text not null check (channel in ('web', 'telegram')),
  telegram_connection_id uuid references public.xavier_telegram_connections(id) on delete set null,
  telegram_chat_id text,
  title text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_message_at timestamptz not null default now()
);

create index if not exists xavier_conversations_user_last_message_idx
  on public.xavier_conversations (user_id, last_message_at desc);

create unique index if not exists xavier_conversations_telegram_identity_idx
  on public.xavier_conversations (telegram_connection_id, telegram_chat_id)
  where channel = 'telegram' and telegram_connection_id is not null and telegram_chat_id is not null;

create table if not exists public.xavier_messages (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  conversation_id uuid not null references public.xavier_conversations(id) on delete cascade,
  channel text not null check (channel in ('web', 'telegram')),
  role text not null check (role in ('user', 'assistant', 'system')),
  content text not null check (char_length(content) between 1 and 12000),
  telegram_message_id bigint,
  telegram_update_id bigint,
  created_at timestamptz not null default now()
);

create index if not exists xavier_messages_user_created_idx
  on public.xavier_messages (user_id, created_at desc);

create index if not exists xavier_messages_conversation_created_idx
  on public.xavier_messages (conversation_id, created_at desc);

create unique index if not exists xavier_messages_telegram_update_idx
  on public.xavier_messages (telegram_update_id)
  where channel = 'telegram' and role = 'user' and telegram_update_id is not null;

create table if not exists public.xavier_memory_summaries (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  conversation_id uuid references public.xavier_conversations(id) on delete cascade,
  summary text not null check (char_length(summary) between 1 and 12000),
  source_message_count integer not null default 0 check (source_message_count >= 0),
  pinned boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists xavier_memory_summaries_user_updated_idx
  on public.xavier_memory_summaries (user_id, updated_at desc);

create unique index if not exists xavier_memory_summaries_conversation_idx
  on public.xavier_memory_summaries (conversation_id)
  where conversation_id is not null;

create table if not exists public.xavier_usage_monthly (
  user_id uuid not null references auth.users(id) on delete cascade,
  month_start date not null,
  message_count integer not null default 0 check (message_count >= 0),
  updated_at timestamptz not null default now(),
  primary key (user_id, month_start)
);

create or replace function public.increment_xavier_usage(
  p_user_id uuid,
  p_month_start date,
  p_limit integer
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  allowed boolean;
begin
  with upserted as (
    insert into public.xavier_usage_monthly (user_id, month_start, message_count)
    values (p_user_id, p_month_start, 1)
    on conflict (user_id, month_start) do update
      set message_count = public.xavier_usage_monthly.message_count + 1,
          updated_at = now()
      where public.xavier_usage_monthly.message_count < p_limit
    returning message_count
  )
  select exists(select 1 from upserted) into allowed;
  return allowed;
end;
$$;

create or replace function public.handle_xavier_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.xavier_profiles (id, display_name)
  values (new.id, coalesce(new.raw_user_meta_data->>'name', split_part(coalesce(new.email, ''), '@', 1)))
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created_xavier on auth.users;
create trigger on_auth_user_created_xavier
after insert on auth.users
for each row execute procedure public.handle_xavier_new_user();

alter table public.xavier_telegram_messages
  add column if not exists user_id uuid references auth.users(id) on delete set null;

alter table public.xavier_telegram_messages
  add column if not exists conversation_id uuid references public.xavier_conversations(id) on delete set null;

create index if not exists xavier_telegram_messages_user_created_idx
  on public.xavier_telegram_messages (user_id, created_at desc);

alter table public.xavier_profiles enable row level security;
alter table public.xavier_telegram_connections enable row level security;
alter table public.xavier_conversations enable row level security;
alter table public.xavier_messages enable row level security;
alter table public.xavier_memory_summaries enable row level security;
alter table public.xavier_usage_monthly enable row level security;

revoke all on table public.xavier_profiles from anon, authenticated;
revoke all on table public.xavier_telegram_connections from anon, authenticated;
revoke all on table public.xavier_conversations from anon, authenticated;
revoke all on table public.xavier_messages from anon, authenticated;
revoke all on table public.xavier_memory_summaries from anon, authenticated;
revoke all on table public.xavier_usage_monthly from anon, authenticated;

grant all on table public.xavier_profiles to service_role;
grant all on table public.xavier_telegram_connections to service_role;
grant all on table public.xavier_conversations to service_role;
grant all on table public.xavier_messages to service_role;
grant all on table public.xavier_memory_summaries to service_role;
grant all on table public.xavier_usage_monthly to service_role;
grant execute on function public.increment_xavier_usage(uuid, date, integer) to service_role;

grant execute on function public.handle_xavier_new_user() to service_role;

comment on table public.xavier_profiles is 'Preferências e limites econômicos por usuário do Xavier.';
comment on table public.xavier_telegram_connections is 'Conexões Telegram por usuário; o token é armazenado somente cifrado no backend.';
comment on table public.xavier_conversations is 'Conversas do Xavier separadas por usuário e canal.';
comment on table public.xavier_messages is 'Histórico textual enxuto do Xavier; não armazena áudio bruto.';
comment on table public.xavier_memory_summaries is 'Memória resumida e controlada do Xavier, sem embeddings na primeira fase.';
comment on table public.xavier_usage_monthly is 'Contador mensal para impedir crescimento e uso inesperados.';
