create table if not exists public.xavier_usage_events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  request_id text,
  channel text not null check (channel in ('web', 'telegram', 'system')),
  event_name text not null check (char_length(event_name) between 1 and 80),
  status text not null default 'success' check (status in ('started', 'success', 'error')),
  provider text,
  model text,
  latency_ms integer check (latency_ms is null or latency_ms >= 0),
  input_tokens integer check (input_tokens is null or input_tokens >= 0),
  output_tokens integer check (output_tokens is null or output_tokens >= 0),
  estimated_cost_usd numeric(12, 8) check (estimated_cost_usd is null or estimated_cost_usd >= 0),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists xavier_usage_events_user_created_idx
  on public.xavier_usage_events (user_id, created_at desc);

create index if not exists xavier_usage_events_event_created_idx
  on public.xavier_usage_events (event_name, created_at desc);

create index if not exists xavier_usage_events_request_idx
  on public.xavier_usage_events (request_id)
  where request_id is not null;

alter table public.xavier_usage_events enable row level security;
revoke all on table public.xavier_usage_events from anon, authenticated;
grant all on table public.xavier_usage_events to service_role;

grant usage, select on sequence public.xavier_usage_events_id_seq to service_role;

comment on table public.xavier_usage_events is 'Telemetria operacional e econômica sem conteúdo privado, usada para medir uso, latência, falhas e custo estimado do Xavier.';
comment on column public.xavier_usage_events.metadata is 'Metadados técnicos sanitizados; nunca armazenar prompts, respostas, áudio, tokens ou credenciais.';
