create table if not exists public.xavier_telegram_messages (
  id bigint generated by default as identity primary key,
  chat_id text not null,
  telegram_user_id bigint,
  telegram_username text,
  role text not null check (role in ('user', 'assistant')),
  content text not null check (char_length(content) between 1 and 12000),
  telegram_message_id bigint,
  telegram_update_id bigint,
  created_at timestamptz not null default now()
);

create index if not exists xavier_telegram_messages_chat_created_idx
  on public.xavier_telegram_messages (chat_id, created_at desc);

create unique index if not exists xavier_telegram_messages_update_id_idx
  on public.xavier_telegram_messages (telegram_update_id)
  where role = 'user' and telegram_update_id is not null;

alter table public.xavier_telegram_messages enable row level security;

revoke all on table public.xavier_telegram_messages from anon, authenticated;
grant all on table public.xavier_telegram_messages to service_role;

comment on table public.xavier_telegram_messages is
  'Histórico privado de conversas do Xavier via Telegram; acessível apenas pelo backend service_role.';
